name: CI

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    tags:
      - '![0-9]+.*'
    paths:
      - '**/**'
      - '!*.md'
      - '!.gitignore'
  pull_request:

jobs:
  lint:
    runs-on: windows-2019
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v4

      - name: Install llvm if necessary
        shell: pwsh
        run: |
          $version = ""
          if (Get-Command "clang-format" -ErrorAction SilentlyContinue){
            $version = clang-format --version
            $pat = ".*\s+(\d+\.\d+\.\d+)"
            if ($version -match $pat) {
              $version = $matches[1]
            }
          }
          if ($version -ne "") {
            Write-Host "clang-format version：$version"
            if ([version]$version -ge [version]"18.1.6") {
              Write-Host "clang-format OK"
            } else {
              Write-Host "clang-format vesion does not meet"
              choco install llvm --version=18.1.6
            }
          } else {
            Write-Host "clang-format not installed"
            choco install llvm --version=18.1.6
          }
      - name: Code style lint
        shell: pwsh
        run: .\clang-format.ps1 -i

  build:
    needs: lint
    runs-on: windows-2019
    strategy:
      matrix:
        arch: [x64, x86]
    steps:

      - name: Checkout last commit
        uses: actions/checkout@v4

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          actions-cache-folder: '.xmake-cache'

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Build weaselfont
        id: build_weaselfont
        run: |
          xmake f -a ${{ matrix.arch }} && xmake

      - name: Compress zip
        run: |
          .\makezip.ps1 -zipFileName weaselfont.${{ matrix.arch }}.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: weaselfont.${{ matrix.arch }}
          path: ./weaselfont.${{ matrix.arch }}.zip

  create_release:
    needs: build
    runs-on: windows-2019
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v4

      - name: Download x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: weaselfont.x64
          path: ./artifacts

      - name: Download x86 artifact
        uses: actions/download-artifact@v4
        with:
          name: weaselfont.x86
          path: ./artifacts

      - name: Create Nightly release
        if: ${{ github.repository == 'fxliang/weaselfont' && github.ref == 'refs/heads/master' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: "Nightly Build"
          files: |
            ./artifacts/weaselfont.x64.zip
            ./artifacts/weaselfont.x86.zip
